name: Mise à jour hebdomadaire AspeDashboard

on:
  schedule:
    - cron: '0 0 * * 0'  # Chaque dimanche à 0h UTC 
  workflow_dispatch:  # Permet un déclenchement manuel

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      RSCONNECT_USER: ${{ secrets.RSCONNECT_USER }}
      RSCONNECT_TOKEN: ${{ secrets.RSCONNECT_TOKEN }}
      RSCONNECT_SECRET: ${{ secrets.RSCONNECT_SECRET }}

    steps:
    - uses: actions/checkout@v4

    - name: Exécuter le script de mise à jour dans Docker
      run: |
        docker run --volume ${{ github.workspace}}:/workspace \
                   --workdir /workspace \
                   -e RSCONNECT_USER="${{ secrets.RSCONNECT_USER }}" \
                   -e RSCONNECT_TOKEN="${{ secrets.RSCONNECT_TOKEN }}" \
                   -e RSCONNECT_SECRET="${{ secrets.RSCONNECT_SECRET }}" \
                   ofbidf/aspedashboard:4.4.2 bash -c "
          Rscript data-raw/prep_data_app.R
        "
        
    - name: Commit fichiers data
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add inst/app/data
        git commit -m "Mise à jour mensuelle des données"
        git push
